export const weatherDetailsConstants = {
  GET_WEATHER_DETAILS_SUCCESS: 'GET_WEATHER_DETAILS_SUCCESS',
  GET_WEATHER_DETAILS_FAILURE: 'GET_WEATHER_DETAILS_FAILURE',
  GET_WEATHER_DETAILS_REQUEST: 'GET_WEATHER_DETAILS_REQUEST',
};
